env = "test"
namespace = "TEST"

[log]
level = "info" # debug, info, warn, error

[server]
port = "8080"
cert_file = ""
key_file = ""

[redis]
host = "127.0.0.1"
port = "6379"
username = ""
password = ""

[job]
interval = 1 # seconds

[rules."*"] # default rule
# <max count per period> <period with millisecond> <max burst> <burst period with millisecond>
limit = [10, 10000, 3, 1000]

[rules."-"] # floor rule
limit = [3, 10000, 1, 1000]

[rules.core]
limit = [200, 10000, 10, 2000]

[rules.core.path]
"POST /v1/file/list" = 2 # quantity, default to 1 if no matched
