name: build
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run build
      run: |
        rustup target add x86_64-unknown-linux-gnu
        cargo build --target x86_64-unknown-linux-gnu --release
        mv target/x86_64-unknown-linux-gnu/release/redlimit ./target/redlimit_amd64
    - uses: actions/upload-artifact@v3
      with:
        name: redlimit
        path: |
          target/redlimit_amd64
